changelog:
  categories:
    - title: Highlights
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - docs
    - title: Other Changes
      labels:
        - "*"
