id = "mikrotik-routeros"
name = "MikroTik RouterOS"
version = "0.1.2"
schema_version = 1
authors = ["Andrey Lebedev"]
description = "RouterOS syntax support and command completion for Zed."
repository = "https://github.com/Azagtot/zed-mikrotik-routeros"

[grammars.bash]
repository = "https://github.com/tree-sitter/tree-sitter-bash"
rev = "a06c2e4415e9bc0346c6b86d401879ffb44058f7"

[language_servers.routeros-lsp]
name = "RouterOS LSP"
languages = ["RouterOS Script"]
